### PR TITLE
Rewrite the service management to leverage Docker Compose

### PR DESCRIPTION
**Pull request by lucatume**
This updates the code to leverage Docker Compose own system of dependency management and IP address resolution.
This results in a less clunky experience, more robust handling of dependencies, speed improvment and less code.

I've added `healthcheck` entries to the base containers to deleagate the complexity of managing their state to Docker Compose.
Depending containers, e.g. the `wordpress` or the `slic` one, can now depend on healthy services.  
Along with this the requirements of the PHP CLI to have the mysql extension installed is gone.

I've also leveraged the `network.aliases` configuration to make sure the `wordpress` service IP is resolved at the network level, avoiding the fetching and setting of IP addresses in the PHP code.

Since I have added it for debugging purposes, I've refined and added the `dc` command to run direct Docker Compose commands in the stack.

Finally, I've introduced a `slic_cache_` API to cache values across the application. Right now a simple array, I'm working on a Redis based solution next (since we have the `redis` service).

[Screencast](https://share.cleanshot.com/VnDMYqc6)

### CODE REVIEW

**Comment by lucatume** [comment]
I've been using this for my day-to-day work on `slic` for a week and I do not seem to have broken anything. I will spin up a TEC build using this branch to test it out in CI context.

**Review by borkweb — APPROVED** [review]
The first time I tried to look at this, I failed to get the containers to fetch (and I tried a bunch of things). I just tried again and it worked like a champ. I'm able to cleanly run tests 🌵 💨

**Comment by borkweb** [comment]
Actually, I'm getting some unexpected errors while running `slic run wpunit` on `the-events-calendar`, so I'm unsure what the deal is.

**Comment by lucatume** [comment]
> Actually, I'm getting some unexpected errors while running `slic run wpunit` on `the-events-calendar`, so I'm unsure what the deal is.

Could you run `slic down && slic reset wp && slic up` and let me know what the issue is?

**Comment by borkweb** [comment]
Perhaps the `slic reset wp` was the key. Runs like a champ, now! Nice and speedy.

**Review by borkweb — APPROVED** [review]

**Pull request merged**
